collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9653409
  lightness: 0.8630504
  brandStrength: 1
  brandColors:
    - '#3A65B4'
    - '#304B5C'
    - '#64A3EC'
    - '#0E1517'
    - '#9B9187'
  rhythmicContrast: 0.8136413
typography_spectrum: 0.8659508
layout_spectrum: 0.9661654
name: 'New York '
